// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'aa02aea7bd6d8b72002d3290e293ed48534b00d4dad87e80b54b126107199d73'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Emprestimo: {
      readonly IdEmprestimo: CodecTypes['pg/text@1']['output'];
      readonly ISBN: CodecTypes['pg/text@1']['output'];
      readonly leitorId: CodecTypes['pg/text@1']['output'];
      readonly DataEmprestimo: CodecTypes['pg/text@1']['output'];
      readonly DataDevolucao: CodecTypes['pg/text@1']['output'];
      readonly Situacao: 'RESERVADO' | 'EMPRESTADO' | 'DEVOLVIDO' | 'ATRASADO';
    };
    readonly Leitor: {
      readonly IdLeitor: CodecTypes['pg/text@1']['output'];
      readonly Cpf: CodecTypes['pg/text@1']['output'];
      readonly Nome: CodecTypes['pg/text@1']['output'];
      readonly Idade: CodecTypes['pg/text@1']['output'];
      readonly Email: CodecTypes['pg/text@1']['output'];
      readonly Telefone: CodecTypes['pg/text@1']['output'];
      readonly Imagem: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Livro: {
      readonly ISBN: CodecTypes['pg/text@1']['output'];
      readonly Nome: CodecTypes['pg/text@1']['output'];
      readonly Autor: CodecTypes['pg/text@1']['output'];
      readonly Ano: CodecTypes['pg/text@1']['output'];
      readonly Quantidade: CodecTypes['pg/text@1']['output'];
      readonly Imagem: CodecTypes['pg/text@1']['output'] | null;
      readonly Genero: CodecTypes['pg/text@1']['output'];
      readonly Sinopse: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Emprestimo: {
      readonly IdEmprestimo: CodecTypes['pg/text@1']['input'];
      readonly ISBN: CodecTypes['pg/text@1']['input'];
      readonly leitorId: CodecTypes['pg/text@1']['input'];
      readonly DataEmprestimo: CodecTypes['pg/text@1']['input'];
      readonly DataDevolucao: CodecTypes['pg/text@1']['input'];
      readonly Situacao: 'RESERVADO' | 'EMPRESTADO' | 'DEVOLVIDO' | 'ATRASADO';
    };
    readonly Leitor: {
      readonly IdLeitor: CodecTypes['pg/text@1']['input'];
      readonly Cpf: CodecTypes['pg/text@1']['input'];
      readonly Nome: CodecTypes['pg/text@1']['input'];
      readonly Idade: CodecTypes['pg/text@1']['input'];
      readonly Email: CodecTypes['pg/text@1']['input'];
      readonly Telefone: CodecTypes['pg/text@1']['input'];
      readonly Imagem: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Livro: {
      readonly ISBN: CodecTypes['pg/text@1']['input'];
      readonly Nome: CodecTypes['pg/text@1']['input'];
      readonly Autor: CodecTypes['pg/text@1']['input'];
      readonly Ano: CodecTypes['pg/text@1']['input'];
      readonly Quantidade: CodecTypes['pg/text@1']['input'];
      readonly Imagem: CodecTypes['pg/text@1']['input'] | null;
      readonly Genero: CodecTypes['pg/text@1']['input'];
      readonly Sinopse: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly emprestimo: {
      readonly DataDevolucao: CodecTypes['pg/text@1']['output'];
      readonly DataEmprestimo: CodecTypes['pg/text@1']['output'];
      readonly IdEmprestimo: CodecTypes['pg/text@1']['output'];
      readonly ISBN: CodecTypes['pg/text@1']['output'];
      readonly leitorId: CodecTypes['pg/text@1']['output'];
      readonly Situacao: 'RESERVADO' | 'EMPRESTADO' | 'DEVOLVIDO' | 'ATRASADO';
    };
    readonly leitor: {
      readonly Cpf: CodecTypes['pg/text@1']['output'];
      readonly Email: CodecTypes['pg/text@1']['output'];
      readonly Idade: CodecTypes['pg/text@1']['output'];
      readonly IdLeitor: CodecTypes['pg/text@1']['output'];
      readonly Imagem: CodecTypes['pg/text@1']['output'] | null;
      readonly Nome: CodecTypes['pg/text@1']['output'];
      readonly Telefone: CodecTypes['pg/text@1']['output'];
    };
    readonly livro: {
      readonly Ano: CodecTypes['pg/text@1']['output'];
      readonly Autor: CodecTypes['pg/text@1']['output'];
      readonly Genero: CodecTypes['pg/text@1']['output'];
      readonly Imagem: CodecTypes['pg/text@1']['output'] | null;
      readonly ISBN: CodecTypes['pg/text@1']['output'];
      readonly Nome: CodecTypes['pg/text@1']['output'];
      readonly Quantidade: CodecTypes['pg/text@1']['output'];
      readonly Sinopse: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly emprestimo: {
      readonly DataDevolucao: CodecTypes['pg/text@1']['input'];
      readonly DataEmprestimo: CodecTypes['pg/text@1']['input'];
      readonly IdEmprestimo: CodecTypes['pg/text@1']['input'];
      readonly ISBN: CodecTypes['pg/text@1']['input'];
      readonly leitorId: CodecTypes['pg/text@1']['input'];
      readonly Situacao: 'RESERVADO' | 'EMPRESTADO' | 'DEVOLVIDO' | 'ATRASADO';
    };
    readonly leitor: {
      readonly Cpf: CodecTypes['pg/text@1']['input'];
      readonly Email: CodecTypes['pg/text@1']['input'];
      readonly Idade: CodecTypes['pg/text@1']['input'];
      readonly IdLeitor: CodecTypes['pg/text@1']['input'];
      readonly Imagem: CodecTypes['pg/text@1']['input'] | null;
      readonly Nome: CodecTypes['pg/text@1']['input'];
      readonly Telefone: CodecTypes['pg/text@1']['input'];
    };
    readonly livro: {
      readonly Ano: CodecTypes['pg/text@1']['input'];
      readonly Autor: CodecTypes['pg/text@1']['input'];
      readonly Genero: CodecTypes['pg/text@1']['input'];
      readonly Imagem: CodecTypes['pg/text@1']['input'] | null;
      readonly ISBN: CodecTypes['pg/text@1']['input'];
      readonly Nome: CodecTypes['pg/text@1']['input'];
      readonly Quantidade: CodecTypes['pg/text@1']['input'];
      readonly Sinopse: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly emprestimo: {
              columns: {
                readonly IdEmprestimo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly ISBN: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly leitorId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly DataEmprestimo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly DataDevolucao: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Situacao: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['IdEmprestimo'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'emprestimo_ISBN_idx_d24ab5fc';
                  readonly prefix: 'emprestimo_ISBN_idx';
                  readonly columns: readonly ['ISBN'];
                  readonly unique: false;
                },
                {
                  readonly name: 'emprestimo_leitorId_idx_d490aaf4';
                  readonly prefix: 'emprestimo_leitorId_idx';
                  readonly columns: readonly ['leitorId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'emprestimo';
                    readonly columns: readonly ['ISBN'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'livro';
                    readonly columns: readonly ['ISBN'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'emprestimo';
                    readonly columns: readonly ['leitorId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'leitor';
                    readonly columns: readonly ['IdLeitor'];
                  };
                },
              ];
            };
            readonly leitor: {
              columns: {
                readonly IdLeitor: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Cpf: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Idade: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Telefone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Imagem: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['IdLeitor'] };
              uniques: readonly [{ readonly columns: readonly ['Cpf'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly livro: {
              columns: {
                readonly ISBN: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Autor: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Ano: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Quantidade: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Imagem: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly Genero: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Sinopse: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['ISBN'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly Situacoes: {
              readonly kind: 'valueSet';
              readonly values: readonly ['RESERVADO', 'EMPRESTADO', 'DEVOLVIDO', 'ATRASADO'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly livro: { readonly namespace: 'public' & NamespaceId; readonly model: 'Livro' };
    readonly leitor: { readonly namespace: 'public' & NamespaceId; readonly model: 'Leitor' };
    readonly emprestimo: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Emprestimo';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Emprestimo: {
            readonly fields: {
              readonly IdEmprestimo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ISBN: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly leitorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly DataEmprestimo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly DataDevolucao: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Situacao: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly leitor: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Leitor';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['leitorId'];
                  readonly targetFields: readonly ['IdLeitor'];
                };
              };
              readonly livro: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Livro';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['ISBN'];
                  readonly targetFields: readonly ['ISBN'];
                };
              };
            };
            readonly storage: {
              readonly table: 'emprestimo';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly IdEmprestimo: { readonly column: 'IdEmprestimo' };
                readonly ISBN: { readonly column: 'ISBN' };
                readonly leitorId: { readonly column: 'leitorId' };
                readonly DataEmprestimo: { readonly column: 'DataEmprestimo' };
                readonly DataDevolucao: { readonly column: 'DataDevolucao' };
                readonly Situacao: { readonly column: 'Situacao' };
              };
            };
          };
          readonly Leitor: {
            readonly fields: {
              readonly IdLeitor: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Cpf: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Idade: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Telefone: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Imagem: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly emprestimos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Emprestimo';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['IdLeitor'];
                  readonly targetFields: readonly ['leitorId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'leitor';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly IdLeitor: { readonly column: 'IdLeitor' };
                readonly Cpf: { readonly column: 'Cpf' };
                readonly Nome: { readonly column: 'Nome' };
                readonly Idade: { readonly column: 'Idade' };
                readonly Email: { readonly column: 'Email' };
                readonly Telefone: { readonly column: 'Telefone' };
                readonly Imagem: { readonly column: 'Imagem' };
              };
            };
          };
          readonly Livro: {
            readonly fields: {
              readonly ISBN: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Autor: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Ano: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Quantidade: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Imagem: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Genero: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Sinopse: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly emprestimos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Emprestimo';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['ISBN'];
                  readonly targetFields: readonly ['ISBN'];
                };
              };
            };
            readonly storage: {
              readonly table: 'livro';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly ISBN: { readonly column: 'ISBN' };
                readonly Nome: { readonly column: 'Nome' };
                readonly Autor: { readonly column: 'Autor' };
                readonly Ano: { readonly column: 'Ano' };
                readonly Quantidade: { readonly column: 'Quantidade' };
                readonly Imagem: { readonly column: 'Imagem' };
                readonly Genero: { readonly column: 'Genero' };
                readonly Sinopse: { readonly column: 'Sinopse' };
              };
            };
          };
        };
        readonly enum: {
          readonly Situacoes: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'RESERVADO'; readonly value: 'RESERVADO' },
              { readonly name: 'EMPRESTADO'; readonly value: 'EMPRESTADO' },
              { readonly name: 'DEVOLVIDO'; readonly value: 'DEVOLVIDO' },
              { readonly name: 'ATRASADO'; readonly value: 'ATRASADO' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
